services:

  identity-link-bff-test:
    container_name: identity-link-bff-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: identity-link-bff-test
    environment:
      APP_SECRET: test
      OIDC_CLIENT_ID: client-id
      OIDC_CLIENT_SECRET: client-secret
    networks:
      - identity-link-network

  identity-link-bff-test-debug:
    extends:
      file: docker-compose-test.yaml
      service: identity-link-bff-test
    container_name: identity-link-bff-test-debug
    volumes:
      - .:/app
    entrypoint: bash
    stdin_open: true
    tty: true

networks:
  identity-link-network:
    driver: bridge